[build]
  command = "npm run build"
  publish = ".next"

[functions]
  included_files = ["./public/success.html"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[forms]
  [forms.contact-form]
    name = "consultation"
    action = "/success"
    method = "POST"
    netlify-honeypot = "bot-field"
